---
- hosts: develop
  become: yes
  user: vagrant
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - vim
        - tmux
        - zsh
        - fish
        - htop
        - iftop
        - python
        - python3
        - ruby
        - golang
        - nodejs
        - npm
        - make
        - curl
        - postgresql
        - libpq-dev
        - nginx
    - name: install packages for rbenv
      apt: name={{item}} update_cache=yes
      with_items:
        - ruby
        - git
        - curl
        - g++
        - make
        - zlib1g-dev
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt-dev
        - sqlite3
        - libsqlite3-dev
        - nodejs
        - gem
