---
- hosts: development_vagrant_box
  sudo: true
  user: vagrant
  tasks:
    - name: install packages
      apt: name={{item}} update_cache=yes
      with_items:
        - ruby
        - git
        - curl
        - g++
        - make
        - zlib1g-dev
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libxml2-dev
        - libxslt-dev
        - sqlite3
        - libsqlite3-dev
        - nodejs
        - gem
